#!/bin/sh

set -e

update-alternatives --install \
    /usr/bin/moc moc "/usr/bin/moc-qt5" "40" \
    --slave /usr/share/man/man1/moc.1.gz moc.1.gz \
    "/usr/share/man/man1/moc-qt5.1.gz"

update-alternatives --install \
    /usr/bin/uic uic "/usr/bin/uic-qt5" "40" \
    --slave /usr/share/man/man1/uic.1.gz uic.1.gz \
    "/usr/share/man/man1/uic-qt5.1.gz"

update-alternatives --install \
    /usr/bin/rcc rcc "/usr/bin/rcc-qt5" "40"

update-alternatives --install \
    /usr/bin/qdbuscpp2xml qdbuscpp2xml "/usr/bin/qdbuscpp2xml-qt5" "40"

update-alternatives --install \
    /usr/bin/qdbusxml2cpp qdbusxml2cpp "/usr/bin/qdbusxml2cpp-qt5" "40"

#DEBHELPER#
