#! /usr/bin/dh-exec
[!armel !armhf] usr/include/*/qt5/QtGlxSupport/5.*/*
[!armel !armhf] usr/include/*/qt5/QtGlxSupport/QtGlxSupport
[!armel !armhf] usr/include/*/qt5/QtGlxSupport/QtGlxSupportDepends
[!armel !armhf] usr/include/*/qt5/QtGlxSupport/QtGlxSupportVersion
[!armel !armhf] usr/include/*/qt5/QtGlxSupport/qtglxsupportversion.h
[!armel !armhf] usr/lib/*/libQt5GlxSupport.a
[!armel !armhf] usr/lib/*/libQt5GlxSupport.prl
[kfreebsd-any linux-any] usr/include/*/qt5/QtEglFSDeviceIntegration/5.*/*
[kfreebsd-any linux-any] usr/include/*/qt5/QtEglFSDeviceIntegration/QtEglFSDeviceIntegration
[kfreebsd-any linux-any] usr/include/*/qt5/QtEglFSDeviceIntegration/QtEglFSDeviceIntegrationDepends
[kfreebsd-any linux-any] usr/include/*/qt5/QtEglFSDeviceIntegration/QtEglFSDeviceIntegrationVersion
[kfreebsd-any linux-any] usr/include/*/qt5/QtEglFSDeviceIntegration/qteglfsdeviceintegrationversion.h
[linux-any] usr/include/*/qt5/QtInputSupport/5.*/*
[linux-any] usr/include/*/qt5/QtInputSupport/QtInputSupport
[linux-any] usr/include/*/qt5/QtInputSupport/QtInputSupportDepends
[linux-any] usr/include/*/qt5/QtInputSupport/QtInputSupportVersion
[linux-any] usr/include/*/qt5/QtInputSupport/qtinputsupportversion.h
[linux-any] usr/lib/*/libQt5InputSupport.a
[linux-any] usr/lib/*/libQt5InputSupport.prl
usr/include/*/qt5/QtAccessibilitySupport/5.*/*
usr/include/*/qt5/QtAccessibilitySupport/QtAccessibilitySupport
usr/include/*/qt5/QtAccessibilitySupport/QtAccessibilitySupportDepends
usr/include/*/qt5/QtAccessibilitySupport/QtAccessibilitySupportVersion
usr/include/*/qt5/QtAccessibilitySupport/qtaccessibilitysupportversion.h
usr/include/*/qt5/QtCore/5.*/*
usr/include/*/qt5/QtDBus/5.*/*
usr/include/*/qt5/QtDeviceDiscoverySupport/5.*/*
usr/include/*/qt5/QtDeviceDiscoverySupport/QtDeviceDiscoverySupport
usr/include/*/qt5/QtDeviceDiscoverySupport/QtDeviceDiscoverySupportDepends
usr/include/*/qt5/QtDeviceDiscoverySupport/QtDeviceDiscoverySupportVersion
usr/include/*/qt5/QtDeviceDiscoverySupport/qtdevicediscoverysupportversion.h
usr/include/*/qt5/QtEglSupport/5.*/*
usr/include/*/qt5/QtEglSupport/QtEglSupport
usr/include/*/qt5/QtEglSupport/QtEglSupportDepends
usr/include/*/qt5/QtEglSupport/QtEglSupportVersion
usr/include/*/qt5/QtEglSupport/qteglsupportversion.h
usr/include/*/qt5/QtEventDispatcherSupport/5.*/*
usr/include/*/qt5/QtEventDispatcherSupport/QtEventDispatcherSupport
usr/include/*/qt5/QtEventDispatcherSupport/QtEventDispatcherSupportDepends
usr/include/*/qt5/QtEventDispatcherSupport/QtEventDispatcherSupportVersion
usr/include/*/qt5/QtEventDispatcherSupport/qteventdispatchersupportversion.h
usr/include/*/qt5/QtFbSupport/5.*/*
usr/include/*/qt5/QtFbSupport/QtFbSupport
usr/include/*/qt5/QtFbSupport/QtFbSupportDepends
usr/include/*/qt5/QtFbSupport/QtFbSupportVersion
usr/include/*/qt5/QtFbSupport/qtfbsupportversion.h
usr/include/*/qt5/QtFontDatabaseSupport/5.*/*
usr/include/*/qt5/QtFontDatabaseSupport/QtFontDatabaseSupport
usr/include/*/qt5/QtFontDatabaseSupport/QtFontDatabaseSupportDepends
usr/include/*/qt5/QtFontDatabaseSupport/QtFontDatabaseSupportVersion
usr/include/*/qt5/QtFontDatabaseSupport/qtfontdatabasesupportversion.h
usr/include/*/qt5/QtGui/5.*/*
usr/include/*/qt5/QtKmsSupport/5.*/*
usr/include/*/qt5/QtKmsSupport/QtKmsSupport
usr/include/*/qt5/QtKmsSupport/QtKmsSupportDepends
usr/include/*/qt5/QtKmsSupport/QtKmsSupportVersion
usr/include/*/qt5/QtKmsSupport/qtkmssupportversion.h
usr/include/*/qt5/QtLinuxAccessibilitySupport/5.*/*
usr/include/*/qt5/QtLinuxAccessibilitySupport/QtLinuxAccessibilitySupport
usr/include/*/qt5/QtLinuxAccessibilitySupport/QtLinuxAccessibilitySupportDepends
usr/include/*/qt5/QtLinuxAccessibilitySupport/QtLinuxAccessibilitySupportVersion
usr/include/*/qt5/QtLinuxAccessibilitySupport/qtlinuxaccessibilitysupportversion.h
usr/include/*/qt5/QtNetwork/5.*/*
usr/include/*/qt5/QtOpenGL/5.*/*
usr/include/*/qt5/QtPlatformCompositorSupport/5.*/*
usr/include/*/qt5/QtPlatformCompositorSupport/QtPlatformCompositorSupport
usr/include/*/qt5/QtPlatformCompositorSupport/QtPlatformCompositorSupportDepends
usr/include/*/qt5/QtPlatformCompositorSupport/QtPlatformCompositorSupportVersion
usr/include/*/qt5/QtPlatformCompositorSupport/qtplatformcompositorsupportversion.h
usr/include/*/qt5/QtPrintSupport/5.*/*
usr/include/*/qt5/QtServiceSupport/5.*/*
usr/include/*/qt5/QtServiceSupport/QtServiceSupport
usr/include/*/qt5/QtServiceSupport/QtServiceSupportDepends
usr/include/*/qt5/QtServiceSupport/QtServiceSupportVersion
usr/include/*/qt5/QtServiceSupport/qtservicesupportversion.h
usr/include/*/qt5/QtSql/5.*/*
usr/include/*/qt5/QtTest/5.*/*
usr/include/*/qt5/QtThemeSupport/5.*/*
usr/include/*/qt5/QtThemeSupport/QtThemeSupport
usr/include/*/qt5/QtThemeSupport/QtThemeSupportDepends
usr/include/*/qt5/QtThemeSupport/QtThemeSupportVersion
usr/include/*/qt5/QtThemeSupport/qtthemesupportversion.h
usr/include/*/qt5/QtWidgets/5.*/*
usr/include/*/qt5/QtXml/5.*/*
usr/lib/*/libQt5AccessibilitySupport.a
usr/lib/*/libQt5AccessibilitySupport.prl
usr/lib/*/libQt5DeviceDiscoverySupport.a
usr/lib/*/libQt5DeviceDiscoverySupport.prl
usr/lib/*/libQt5EglSupport.a
usr/lib/*/libQt5EglSupport.prl
usr/lib/*/libQt5EventDispatcherSupport.a
usr/lib/*/libQt5EventDispatcherSupport.prl
usr/lib/*/libQt5FbSupport.a
usr/lib/*/libQt5FbSupport.prl
usr/lib/*/libQt5FontDatabaseSupport.a
usr/lib/*/libQt5FontDatabaseSupport.prl
usr/lib/*/libQt5KmsSupport.a
usr/lib/*/libQt5KmsSupport.prl
usr/lib/*/libQt5LinuxAccessibilitySupport.a
usr/lib/*/libQt5LinuxAccessibilitySupport.prl
usr/lib/*/libQt5PlatformCompositorSupport.a
usr/lib/*/libQt5PlatformCompositorSupport.prl
usr/lib/*/libQt5ServiceSupport.a
usr/lib/*/libQt5ServiceSupport.prl
usr/lib/*/libQt5ThemeSupport.a
usr/lib/*/libQt5ThemeSupport.prl
